# Generated by Django 3.2.13 on 2022-05-10 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eveuniverse", "0007_evetype_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("delete_structure", "Can delete structure"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power_mode",
                    models.CharField(
                        choices=[
                            ("FU", "Full Power"),
                            ("LO", "Low Power"),
                            ("AB", "Abandoned"),
                            ("LA", "Abandoned?"),
                            ("UN", "Unknown"),
                        ],
                        help_text="Power mode of the structure",
                        max_length=2,
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="date this structure was last updated from the EVE server",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the structure", max_length=255
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="The owner of the structure", max_length=255
                    ),
                ),
                (
                    "reinforce_hour",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Default reinforcement hour of this structure",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(23)],
                    ),
                ),
                (
                    "eve_solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evesolarsystem",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        help_text="type of the structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StructureModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("Highslot", "Highslot"),
                            ("Midslot", "Medslot"),
                            ("Lowslot", "Lowslot"),
                            ("Rigslot", "Rigslot"),
                            ("Service", "Service"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        help_text="eve type of the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        help_text="Structure this item is located in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="structureintel.structure",
                    ),
                ),
            ],
        ),
    ]
